version: '3.4'
services:
  api:
    build: 
      context: .
    container_name: k8s-api-example
    image: revazashvili/k8s-api-example:1.0.0
    ports:
      - 8081:80
    volumes:
      - ./src/:/api
    # working_dir: /api
    # entrypoint: /bin/bash
    # stdin_open: true
    # tty: true
    