version: '3.4'
services:
  api:
    build: 
      context: .
    container_name: k8s-api-example
    image: revazashvili/k8s-api-example:1.0.0
    ports:
      - 8081:80
    volumes:
      - ./src/:/api
      - ./config/appsettings.Production.json:/app/appsettings.Production.json
    environment:
      - POSTGRES_USER=bGV2YW5yZXZhemFzaHZpbGl1c2VybmFtZQ==
      - POSTGRES_PASSWORD=bGV2YW5yZXZhemFzaHZpbGlwYXNzd29yZA==
    # working_dir: /api
    # entrypoint: /bin/bash
    # stdin_open: true
    # tty: true
  
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=bGV2YW5yZXZhemFzaHZpbGl1c2VybmFtZQ==
      - POSTGRES_PASSWORD=bGV2YW5yZXZhemFzaHZpbGlwYXNzd29yZA==
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local