apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api-deployment
  namespace: golang
  labels:
    app: golang-api
  annotations:
spec:
  selector:
    matchLabels:
      app: golang-api
  replicas: 2
  # make sure that at deployment time at least one instance is alive and takes requests
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
      - name: golang-api
        image: revazashvili/k8s-go-api-example:1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "500m"