apiVersion: v1
Kind: Service
metadata:
  app: golang-api-service
  namespace: golang
spec:
  type: LoanBalancer
  selector:
    app: golang-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080