apiVersion: v1
kind: Service
metadata:
  name: golang-api-service
  namespace: golang
spec:
  type: LoadBalancer
  selector:
    app: golang-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080