apiVersion: v1
kind: Service
metadata:
  name: csharp-api-service
  namespace: csharp
spec:
  type: LoadBalancer
  selector:
    app: csharp-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80